jsprocessor for simplewallet
askmish/sawtooth-simplewallet pull request #10
Opened 2018-06-01 09:25 UTC by varasudha194

jsprocessor for simplewallet
Signed-off-by: test <varalakshmi.ka@intel.com>

2018-06-01 20:49 UTC, danintel requested changes
Spelling error in SimpleWalletHandler.js.

2018-06-01 20:49 UTC, danintel commented on jsprocessor/SimpleWalletHandler.js
> +const makeTransfer =(context, senderAddress, amount, recieverAddress)  => (possibleAddressValues) => {
Receiver and receiver are misspelled throughout this file:

s/eciever/eciever/g

2018-06-05 13:25 UTC, danintel approved these changes

2018-06-06 07:00 UTC, askmish requested changes

2018-06-06 07:00 UTC, askmish commented on jsprocessor/SimpleWalletHandler.js
> +        // Select the action to e performed
Please fix Indentation and spelling errors.

2018-06-06 07:00 UTC, askmish commented on jsprocessor/package.json
> +  "name": "sawtooth-sdk",
please update the package.json for jsprocessor.

2018-06-06 07:00 UTC, askmish commented on jsprocessor/package.json
> +  "name": "sawtooth-sdk",
Refer jsclient package.json for example

2018-06-13 16:02 UTC, askmish approved these changes

2018-06-13 16:03 UTC, merged

2018-06-13 16:29 UTC, danintel reviewed
I think the jsprocessor should have the same default validator address as the other transaction processors.  See in-line comment.

2018-06-13 16:29 UTC, danintel commented on jsprocessor/SimpleWalletHandler.js
> +    console.log("Sender balance:"+senderNewBalance+", Reciever balance:"+receiverNewBalance)
s/Reciever/Receiver/

2018-06-13 16:29 UTC, danintel commented on jsprocessor/index.js
> +const address = process.argv[2]
All the other simplewallet transaction processors have a default for the validator URL.  I suggest something like:

```javascript
const DEFAULT_URL = 'tcp://validator:4004'

// . . .

var address = DEFAULT_URL
if (process.argv.length >= 3) {
  address = process.argv[2]
}
```