Add jsclient to simplewallet
askmish/sawtooth-simplewallet pull request #5
Opened 2018-05-18 11:33 UTC by prp20

Co-authored-by: Ashish K Mishra<ashish.k.mishra@intel.com>

Signed-off-by: Prasad P R <ppprasad112@gmail.com>

2018-05-22 13:23 UTC, askmish requested changes

2018-05-22 13:23 UTC, askmish commented on jsclient/app.js
> +//app.use('/users', users);
Could you remove this redundant comment.

2018-05-22 13:23 UTC, askmish commented on jsclient/public/js/main.js
> +    if (amount == 0 || amount == " ") {
amount should be verified with empty string rather than a space?

2018-05-22 13:23 UTC, askmish commented on jsclient/public/js/main.js
> +    if (amount == 0 || amount == " ") {
This comment is applicable to other parts of the code.

2018-05-22 13:23 UTC, askmish commented on jsclient/public/js/main.js
> +    }else if(beneficiary == ""){
This should be just another if condition, instead of else if.

2018-05-22 13:23 UTC, askmish commented on jsclient/routes/SimpleWalletClient.js
> +        const privateKeyStr = privateKeyStrBuf.toString().trim();
Extra space in indentation.

2018-05-22 13:23 UTC, askmish commented on jsclient/routes/SimpleWalletClient.js
> +        this.address = hash("simplewallet").substr(0, 6) + hash(this.publicKey).substr(0, 64);
Exra space in indentation.

2018-05-22 13:23 UTC, askmish commented on jsclient/routes/SimpleWalletClient.js
> +	var userpubkeyfile = '/root/.sawtooth/keys/'+userid+'.pub';
Indentation.

2018-05-22 13:23 UTC, askmish commented on jsclient/routes/SimpleWalletClient.js
> +
Indentation and remove empty line.

2018-05-22 13:23 UTC, askmish commented on jsclient/routes/SimpleWalletClient.js
> +	console.log("sending = " + payloadBytes);
This console log is not required. Please remove.

2018-05-22 13:23 UTC, askmish commented on jsclient/routes/SimpleWalletClient.js
> +       		 });
Indentation.

2018-05-22 13:23 UTC, askmish commented on jsclient/routes/SimpleWalletClient.js
> +            	batches: [batch]
Indentation.

2018-05-22 13:23 UTC, askmish commented on jsclient/routes/SimpleWalletClient.js
> +
Empty line.

2018-05-22 13:23 UTC, askmish commented on jsclient/routes/SimpleWalletClient.js
> +                    var geturl = 'http://rest-api:8008/state/'+this.address
Indentation.

2018-05-22 13:23 UTC, askmish commented on jsclient/routes/SimpleWalletClient.js
> + 		    method: 'POST',
Indentation.

2018-05-22 13:23 UTC, askmish commented on jsclient/routes/index.js
> +    var x = client.balance();
A better variable name instead of just 'x'.

2018-05-23 21:33 UTC, danintel commented
Since you're adding a JavaScript client, you need to add JavaScript to the list of supported clients in README.md under `Components`  and `Contributing`.

2018-05-23 21:34 UTC, danintel requested changes
Since you're adding a JavaScript client, you need to add JavaScript to the list of supported clients in README.md under Components and Contributing.

2018-05-24 16:22 UTC, danintel approved these changes

2018-05-25 12:45 UTC, askmish approved these changes

2018-05-25 12:45 UTC, merged